export { default as users } from './users/mutations'
export { default as auth } from './auth/mutations'
export { default as windows } from './windows/mutations'
export { default as notes } from './notes/mutations'
export { default as dictionary } from './dictionary/mutations'
