export { default as users } from './users/queries'
export { default as windows } from './windows/queries'
export { default as auth } from './auth/queries'
export { default as notes } from './notes/queries'
export { default as dictionary } from './dictionary/queries'
